name: pubspec_lock_reader
description: Read pubspec.lock file
version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  yaml: ^3.1.0

dev_dependencies:
  effective_dart: ^1.3.1
  test: ^1.16.8
